
#ifndef _TIMER0_CONFIG_H
#define _TIMER0_CONFIG_H

/*
 TIMERX_NORMAL
 TIMERX_CTC
 TIMERX_FAST_PWM
 TIMERX_PHASE_PWM 	
*/

#define TIMER0_MODE TIMER0_NORMAL

/*
TIMER0_DIV_BY_1			
TIMER0_DIV_BY_8			
TIMER0_DIV_BY_64		
TIMER0_DIV_BY_256		
TIMER0_DIV_BY_1024		
*/
#define TIMER0_PRESCALER  TIMER0_DIV_BY_1024

/*
 TIMER0_NO_ACTION	
 TIMER0_TOGGLE		
 TIMER0_SET	     //inverted 
 TIMER0_CLEAR	// Non-inverted					
*/

#define TIMER0_COM_EVENT   TIMER0_NO_ACTION


#endif
